name: Deploy backend to Deno Deploy

on:
  push:
    paths:
      - 'deno_api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Deno
        uses: denoland/deployctl@v1
        with:
          project: imdb-search-omar2205
          entrypoint: main.ts
          root: deno_api
          token: ${{ secrets.GH_TOTASKS_DEPLOY }}
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.GH_TOTASKS_DEPLOY }}
